"""Spectral--GW objects used by the strong theory-aligned extractor."""

from .spectral_gw import (
    DifferentiableGWLoss,
    GWResult,
    HeatKernelMetricBuilder,
    HeatKernelState,
    IdentityCouplingGWResult,
    LaplacianFidelityResult,
    SignedLaplacianBuilder,
    SpectralState,
    SpectralStateExtractor,
    gw_identity_coupling_upper_bound,
    laplacian_fidelity_metrics,
    spectral_w1,
    spectral_winf_dense,
    spectral_winf_exact,
)
from .evaluation import (
    EvolutionRepresentation,
    FidelityResult,
    HardExportFidelityEvaluator,
    HardUnionGraph,
    SpectralGWEvolutionEncoder,
    SpectralGWGreedyExporter,
    TheoryBoundEvaluator,
    build_hard_union_graph,
    one_step_sgw_error_bound,
)

__all__ = [
    "DifferentiableGWLoss",
    "GWResult",
    "HeatKernelMetricBuilder",
    "HeatKernelState",
    "IdentityCouplingGWResult",
    "LaplacianFidelityResult",
    "SignedLaplacianBuilder",
    "SpectralState",
    "SpectralStateExtractor",
    "gw_identity_coupling_upper_bound",
    "laplacian_fidelity_metrics",
    "spectral_w1",
    "spectral_winf_dense",
    "spectral_winf_exact",
    "EvolutionRepresentation",
    "FidelityResult",
    "HardExportFidelityEvaluator",
    "HardUnionGraph",
    "SpectralGWEvolutionEncoder",
    "SpectralGWGreedyExporter",
    "TheoryBoundEvaluator",
    "build_hard_union_graph",
    "one_step_sgw_error_bound",
]
