"""Spectral--GW objects used by the strong theory-aligned extractor."""

from .spectral_gw import (
    DifferentiableGWLoss,
    GWResult,
    HeatKernelMetricBuilder,
    HeatKernelState,
    IdentityCouplingGWResult,
    LaplacianFidelityResult,
    SignedLaplacianBuilder,
    SpectralState,
    SpectralStateExtractor,
    gw_identity_coupling_upper_bound,
    laplacian_fidelity_metrics,
    spectral_w1,
    spectral_winf_dense,
    spectral_winf_exact,
)
from .evaluation import (
    CandidateScoreStandardizer,
    EvolutionRepresentation,
    FidelityResult,
    HardExportFidelityEvaluator,
    HardUnionGraph,
    HardUnionGraphBuilder,
    SpectralGWEvolutionEncoder,
    SpectralGWGreedyExporter,
    TheoryBoundEvaluator,
    build_hard_union_graph,
    one_step_sgw_error_bound,
)
from .tg_features import (
    SGWFeatureExtractor,
    SGWSequenceFeatures,
    SGWTheoryFeatureConfig,
    SGWWindowState,
    TGSGWFeatureArtifact,
    load_tg_sgw_feature_artifact,
    save_tg_sgw_feature_artifact,
)

__all__ = [
    "DifferentiableGWLoss",
    "GWResult",
    "HeatKernelMetricBuilder",
    "HeatKernelState",
    "IdentityCouplingGWResult",
    "LaplacianFidelityResult",
    "SignedLaplacianBuilder",
    "SpectralState",
    "SpectralStateExtractor",
    "gw_identity_coupling_upper_bound",
    "laplacian_fidelity_metrics",
    "spectral_w1",
    "spectral_winf_dense",
    "spectral_winf_exact",
    "EvolutionRepresentation",
    "CandidateScoreStandardizer",
    "FidelityResult",
    "HardExportFidelityEvaluator",
    "HardUnionGraph",
    "HardUnionGraphBuilder",
    "SpectralGWEvolutionEncoder",
    "SpectralGWGreedyExporter",
    "TheoryBoundEvaluator",
    "build_hard_union_graph",
    "one_step_sgw_error_bound",
    "SGWFeatureExtractor",
    "SGWSequenceFeatures",
    "SGWTheoryFeatureConfig",
    "SGWWindowState",
    "TGSGWFeatureArtifact",
    "load_tg_sgw_feature_artifact",
    "save_tg_sgw_feature_artifact",
]
